### ISSUE TITLE
TypeError: set_camera_extrinsics(): incompatible function arguments.

### ISSUE THREAD

**Issue by ChristianMilianti** [jc211/NeRFCapture#1]
Hey Jad,
Really cool project!

I'm trying to run it on an iPhone 13 Pro Max, but I run into the following error when I try to send an image from my phone to instant-ngp when I run the following command  $python scripts/nerfcapture2nerf.py --stream.

Do you know what the problem could be?

![Screenshot from 2023-03-21 18-56-18](https://user-images.githubusercontent.com/66559598/226546643-c4012131-238b-47e5-971d-1f6d708bbda0.png)

Cheers!
Christian

**Comment by jc211** [comment]
Hey Christian,
Problem should be solved after the latest merge in instantngp

**Comment by ChristianMilianti** [comment]
Thanks for that Jad, that seems to have worked!
Another question I have is when I run 

`python scripts/nerfcapture2nerf.py --stream`

the images are sent to instant-ngp and I can see them fine, but I'm not sure how to visualise the nerf that is being trained? On the other hand, If I first save the captured images using 

`python scripts/nerfcapture2nerf.py --save_path "dir1/dir2" --n_frames 20 `

and then drag and drop the saved folder into instant-ngp the nerf is created.

Do you know how to visualise the nerf directly when `python scripts/nerfcapture2nerf.py --stream` is run?

**Comment by jc211** [comment]
Hey, if the gui is coming up, when first image comes in, are you starting
the training by pressing “t” or by pressing the green button? Make sure the
images are captured around the origin otherwise training wont work.

**Comment by ChristianMilianti** [comment]
By pressing the green button

**Comment by jc211** [comment]
Could be the images are taken too far away from the unit box?

**Comment by ChristianMilianti** [comment]
Here's a video of what I mean

I can get the images to be sent from my phone to instant-ngp no problem using `python scripts/nerfcapture2nerf.py --stream`

But when I click start training, I'm not sure how to visualise the actual nerf that is being trained, I can only pan around the images that I've taken. 

Whereas if I first save the images using `python scripts/nerfcapture2nerf.py --save_path "dir1/dir2" --n_frames 20`, and then simply drag and drop the saved folder, the nerf visualisation automatically appears.

https://user-images.githubusercontent.com/66559598/226764910-ac618136-d3db-4ab0-81f4-af44d17c4522.mp4

**Comment by ChristianMilianti** [comment]
Ahhhhh yes, it automatically defaulted to that it seems.

Thanks for your assistance, that worked! :)
