### ISSUE TITLE
Renders are dusty and have weird color effects

### ISSUE THREAD

**Issue by Avuerro** [jc211/NeRFCapture#5]
Hi, thanks for your work. 

I'm currently experimenting with nerfcapture and instant-ngp. However, for some reason the renders have dust cloud effects as well as weird colorings. There are some small color specks visible, but it looks almost grayscale. Do you have any idea as to why this could be the case? These problems do not occur when working with photos or videos and preprocessing them with the scripts provided by instant-ngp.

**Comment by jc211** [comment]
I am not sure why there is a difference. I assume it may have to do with the accuracy of the poses. I've found disabling random background colors in the training settings helps remove the grayishness.

**Comment by Avuerro** [comment]
Thanks! That already helps a lot, I also experimented with other datasets and I'm getting better results now.
