### ISSUE TITLE
Network Config does not exist

### ISSUE THREAD

**Issue by jonstephens85** [jc211/NeRFCapture#6]
I installed the app on my iPhone 14 Pro and ran cycloneddps. It identifies my iPhone so I am getting a connection. When I run: python scripts/nerfcapture2nerf.py --stream to launch the app with Instant-NGP, I get an runtime error: 

```
16:37:05 SUCCESS  Initialized Vulkan and NGX on device #0: NVIDIA GeForce RTX 3090 Ti
16:37:06 INFO     Loading network config from:
Traceback (most recent call last):
  File "C:\Users\jonat\Instant-NGP-20230404\scripts\nerfcapture2nerf.py", line 241, in <module>
    live_streaming_loop(reader, args.n_frames)
  File "C:\Users\jonat\Instant-NGP-20230404\scripts\nerfcapture2nerf.py", line 82, in live_streaming_loop
    testbed.reload_network_from_file()
RuntimeError: Network config  does not exist.
```

I am not sure what I am doing wrong on my end.

**Comment by jc211** [comment]
Hi Jon,
Can you run normal instant ngp via python? I think its something like python scripts/run.py

**Comment by jonstephens85** [comment]
That may be it. I specially did a fresh pull an recompiled the newest version of Instant-NGP. Running the Fox project is not working. I am getting an odd error. I will try troubleshooting my install and report back.

I'd like to get this working. I wrote the Instant NeRF getting started guide for NVIDIA's technical blog. Once I get this working, I will make a tutorial video and share it with NVIDIA to see if they will update the technical blog with Nerfcapture.

**Comment by jc211** [comment]
It should work out of the box - that being said, for debugging purposes, you could try hardcoding the path to the config file in the code:
Line 82 in nerfcapture2nerf - Replace:
```python
testbed.reload_network_from_file()
```
with
```python
testbed.reload_network_from_file("/path/to/config/")
```

**Comment by jonstephens85** [comment]
I compiled Instant-NGP and it fixed the issue. Thank you!
