### ISSUE TITLE
Images coming in sideways

### ISSUE THREAD

**Issue by jonstephens85** [jc211/NeRFCapture#7]
<img width="1915" alt="Sideways images" src="https://user-images.githubusercontent.com/82414293/230642694-c1f506e9-b2c9-444d-9a67-3a38aab57b89.png">
I tested the app and the images come in rotated 90 degrees. Is the app intended to be ran holding the phone horizontally?

**Comment by jc211** [comment]
The ARKit coordinate system aligns the X axis with the long side of the phone. As a consequence, when you press G on  instantngp, the portrait images will appear rotated by 90 degrees. I usually take one of the photos in landscape so that when you snap to it in ngp, the viewer is aligned properly.
